---
- name: Backup MikroTik Configuration
  hosts: mikrotik
  gather_facts: no
  tasks:
    - name: Pull configuration from MikroTik
      ansible.netcommon.cli_command:
        command: /export
      register: config_output

    - name: Display configuration
      debug:
        msg: "{{ config_output.stdout }}"
