---
- name: Backup MikroTik Configuration
  hosts: routers
  gather_facts: no
  tasks:
    - name: Pull configuration from MikroTik
      ansible.netcommon.cli_command:
        command: /export
      register: config_output

    - name: Display configuration
      debug:
        var: config_output.stdout_lines
