---
- name: RouterOS print IP addresses
  hosts: routers
  gather_facts: false
  tasks:
    - name: Run command
      community.routeros.command:
        commands:
          - /system resource print
      register: print_path
    - name: Print the result
      ansible.builtin.debug:
        var: print_path.msg
