#Gather IP addresses on router - Why isnt this working?
---
- name: Retrieve MikroTik IP Addresses
  hosts: routers
  gather_facts: no
  tasks:
    - name: Get IP addresses
      ansible.netcommon.cli_command:
        command: /ip address print
      register: ip_output

    - name: Display IP addresses
      debug:
        msg: "{{ ip_output.stdout }}"

