#Create Survey Variables with usr-name and pword. Set hosts to router group appropriately
---
- name: "Find and set the user password with supplied info"
  hosts: routers
  vars:
  gather_facts: false
  tasks:
    - name: Run command
      community.routeros.command:
        commands:
          - /user add group=full name=1234 password=1234
