#Create Survey Variables with dst-address and gayeway. Set hosts to router group appropriately
---
- name: Add Routes to MikroTik
  hosts: routers
  gather_facts: no
  tasks:
    - name: Add route to {{ dst-address }}
      ansible.netcommon.cli_command:
        command: /ip route add dst-address={{ dst-address }} gateway={{ gateway }}
