#Create Survey Variables with dstaddress and gayeway. Set hosts to router group appropriately
---
- name: Add Routes to MikroTik
  hosts: routers
  gather_facts: no
  tasks:
    - name: Add route to {{ dstaddress }}
      community.routeros.command:
        commands: /ip route add dst-address={{ dstaddress }} gateway={{ gateway }}
