---
- name: "Find and set the user password with supplied info"
  hosts: routers
  gather_facts: false
  tasks:
    - name: Run command
      community.routeros_command:
        commands:
          - /user set [/user find where name={{ usr_name }}] password={{ pword }}
